### PR TITLE
Tweaks for the Profile Popout

### PR DESCRIPTION
**Pull request by xenrelle**
makes the username and status not so close to the bottom of the dark gray area, also removes the dark circle around the status icon if the profile has custom colours (very specific i know lmao)

Before: Before Preview

After: After Preview

### CODE REVIEW

**Comment by xenrelle** [comment]
also I just noticed the status message should be centered but it doesnt work properly, i'll see if i can fix that

**Comment by xenrelle** [comment]
too tired to try making the emojis centered lmao

**Comment by DaMoyai** [comment]
> too tired to try making the emojis centered lmao

lmao ill try that for u dw

**Comment by xenrelle** [comment]
managed to fix it myself, I made a new pull request

**Pull request merged**
