### PR TITLE
Fixes User Card in Settings

### PR DESCRIPTION
**Pull request by xenrelle**
fixes the "my account" and "profiles" cards, idk what else to call them lol
it also makes them look more accurate to their old looks but I can't remove the svg mask for where the status icon is supposed to be thanks css >:(
code is probably messy but it works so

**before:**
Before1
Before2

**after:**
after1
after2

### CODE REVIEW

**Comment by xenrelle** [comment]
i was basing it off of this screenshot from a 2020 youtube video so its not fully accurate but close enough lmao
image

**Comment by xenrelle** [comment]
fixed a goofy bug where if a profile had nitro but without a banner it would fill the banner colour with the pfp's primary colour or something idk
also the dark circle remained so i fixed that

**before**:
before1

**after**:
after1

**Comment by DaMoyai** [comment]
lmao you basically the new maintainer 🤝

fr tho, appreciate how you just fix the most random location

**Comment by xenrelle** [comment]
np, glad to help out :)

**Pull request merged**
